---
version: '3'

dotenv: ['.env']

tasks:
  encrypt:
    desc: Encrypt files using SOPS
    preconditions:
      - sh: test -f .env
        msg: ".env file doens't exist"
    cmds:
      - sops -e --input-type dotenv --output-type dotenv .env > .env.enc

  decrypt:
    desc: Decrypt files using SOPS
    preconditions:
      - sh: test -f .env.enc
        msg: ".env.enc doesn't exist"
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env

  coverage:
    desc: Run tests and show coverage summary
    cmds:
      - cargo llvm-cov --workspace --all-features --summary-only

  coverage:report:
    desc: Generate coverage reports (lcov and html)
    cmds:
      - cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info
      - cargo llvm-cov --workspace --all-features --html

  coverage:upload:
    desc: Upload coverage report to Coveralls
    precondition:
      - sh: test -f lcov.info
        msg: "lcov.info doesn't exist"
    cmds:
      - coveralls report lcov.info  -n -r {{ .COVERALLS_REPO_TOKEN }}
    silent: true

  build:
    desc: Build the project for the host architecture
    cmds:
      - cargo build

  build:local:
    desc: Build the project natively (alias for build)
    cmds:
      - task: build

  build:amd64:
    desc: Cross-compile the project for AMD64 (x86_64-unknown-linux-gnu)
    cmds:
      - cross build --target x86_64-unknown-linux-gnu --release

  build:arm64:
    desc: Cross-compile the project for ARM64 (aarch64-unknown-linux-gnu)
    cmds:
      - cross build --target aarch64-unknown-linux-gnu --release

  build:armv7:
    desc: Cross-compile the project for ARMv7 (armv7-unknown-linux-gnueabihf)
    cmds:
      - cross build --target armv7-unknown-linux-gnueabihf --release

  build:armv6:
    desc: Cross-compile the project for ARMv6 (arm-unknown-linux-gnueabihf)
    cmds:
      - cross build --target arm-unknown-linux-gnueabihf --release

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt --all

  test:
    desc: Run all tests (fmt, lint, and unit tests)
    cmds:
      - task: fmt:check
      - task: lint
      - CI=true cargo test --lib --tests

  test:ci:
    desc: Run tests using the CI profile
    cmds:
      - task: fmt:check
      - task: lint
      - CI=true cargo test --lib --tests --profile ci

  lint:
    desc: Run clippy for linting
    cmds:
      - cargo clippy -- -D warnings

  clippy:
    desc: Run cargo clippy (alias for lint)
    cmds:
      - task: lint

  fmt:check:
    desc: Check code formatting with rustfmt
    cmds:
      - cargo fmt -- --check

  check:
    desc: Run all checks (format, lint, test)
    cmds:
      - task: fmt:check
      - task: lint
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  default:
    cmds:
      - task -l
    silent: true
