version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - cargo build

  test:
    desc: Run all tests (fmt, lint, and unit tests)
    cmds:
      - task: fmt:check
      - task: lint
      - CI=true cargo test --lib --tests

  test:ci:
    desc: Run tests using the CI profile
    cmds:
      - task: fmt:check
      - task: lint
      - CI=true cargo test --lib --tests --profile ci

  lint:
    desc: Run clippy for linting
    cmds:
      - cargo clippy -- -D warnings

  clippy:
    desc: Run cargo clippy (alias for lint)
    cmds:
      - task: lint

  format:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt --all

  fmt:check:
    desc: Check code formatting with rustfmt
    cmds:
      - cargo fmt -- --check

  check:
    desc: Run all checks (format, lint, test)
    cmds:
      - task: fmt:check
      - task: lint
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
