pub mod bulk_manage_downloads;
pub mod check_health;
pub mod configure_aria2;
pub mod inspect_download;
pub mod manage_all_instances;
pub mod manage_downloads;
pub mod manage_torrent;
pub mod monitor_queue;
pub mod organize_completed;
pub mod registry;
pub mod schedule_limits;
pub mod search_downloads;

pub use bulk_manage_downloads::BulkManageDownloadsTool;
pub use check_health::CheckHealthTool;
pub use configure_aria2::ConfigureAria2Tool;
pub use inspect_download::InspectDownloadTool;
pub use manage_all_instances::ManageAllInstancesTool;
pub use manage_downloads::ManageDownloadsTool;
pub use manage_torrent::ManageTorrentTool;
pub use monitor_queue::MonitorQueueTool;
pub use organize_completed::OrganizeCompletedTool;
pub use registry::{McpeTool, ToolRegistry};
pub use schedule_limits::ScheduleLimitsTool;
pub use search_downloads::SearchDownloadsTool;
